# (PART)  Inferencia estadística {-}
# Variables aleatorias
```{definition,name="Variable aleatoria"}
Sea $\Omega$ un espacio muestral asociado a una experimento aleatorio $\epsilon$ y $\omega\in\Omega$,  entonces se genera la función **variable aleatoria** 
\begin{align*}
  X:\Omega&\longrightarrow \mathbb{R}\\
  \omega&\longmapsto X(\omega)
\end{align*}
```
\(R_{X}=\{x\in \mathbb {R} /\ \exists \,\omega \in \Omega :X(\omega )=x\}\)
es decir a cada elemento de $\Omega$ se le asocia un número real $\mathbb{R}$, además la probabilidad de $x\in \mathbb{R}$ es $P[x]= \sum^{n}_{i=1}P\left[\omega_i\right]$ donde $\omega_i\in X^{-1}(x)$. La definición indica por otro lado que un espacio muestral $\Omega$ puede genera diferentes variables aleatorias. 


```{example}
El espacio muestral de lanzar una monedas tres veces es $$\omega= \left\{ccc,ccs,csc,scc,css,scs,ssc,sss\right\}$$ además sea $n_c$ es número de caras y $n_s$ el número de sellos, es posibles generar dos o mas variables aleatorias por ejemplo:

1. $X(\omega)=n_c$ entonces el rango de $X$ es $R_X \left\{3,2,1,0\right\}$
pues \begin{align*}
  3&=X(ccc)&\\
  2&=X(ccs)=X(csc)=X(scc)&\\
  1&=X(css)=X(scs)=X(ssc)&\\
  0&=X(sss)&
\end{align*}
2. $X(\omega)=n_c-n_s$ entonces las imagenes de $X$ son $R_X= \left\{3,1,-1,-3\right\}$ en efecto 
\begin{align*}
  3&=X(ccc)&\\
  1&=X(ccs)=X(csc)=X(scc)&\\
  -1&=X(css)=X(scs)=X(ssc)&\\
  -3&=X(sss).&
\end{align*}

Estos subconjuntos de $\mathbb{R}$ también son espacios muestrales pues el conjunto de elementos de $\Omega$ con imagen dentro de estos valores reales $x$ en $\mathbb{R}$ es un elemento de $2^{\Omega}$ es decir un evento por lo tanto tiene una determinada probabilidad $P[x]$, en el primer caso $X(\omega)=n_c$ tienen probabilidades  
\begin{align*}
  P(3)&=P[ccc]= \frac{1}{8}\\
  P(2)&=P[ccs]=P[csc]=P[scc]=\frac{3}{8}\\
  P(1)&=P[css]=P[scs]=P[ssc]=\frac{3}{8}\\
  P(0)&=P[sss]=\frac{1}{8}
\end{align*}
que es lo mismo para el segundo caso $X(\omega)=n_c-n_s$.

```

```{definition,name="Eventos equivalentes"}
Sea $\Omega$ un espacio muestral asociado a una experimento aleatorio $\epsilon$ y $X$ una variable aleatoria con rango $R_X$ definida sobre $\Omega$. Dos eventos $W\in\Omega$ y $E_X\in R_X$ son **eventos equivalentes** si  existe la relación
\[W= \left\{\omega\in\Omega/X(\omega)=E_X\right\}\] es decir $E_X$ consta de todos los elementos en $\Omega$ para los cuales $X(\omega)\in W$
```
## Clases de variables aleatorias
### Variable aleatoria discreta
Cuando el rango de la variable aleatoria $X$, \(R_X\)  es *finito* o *infinito* contable (no necesarimente enteros)
\(R_X= \left\{x_1,x_2,\ldots,x_n\ldots\right\}\)



### Variable aleatoria continua

\(R_X\) abarca cualquier intervalo en la recta numerica





### Variable aleatoria mixta
Discreta y continua




## Función de probabilidad de una variable aleatoria 

### Función de probabilidad de una variable aleatorias discreta
```{definition,name="Función o ley de probabilidad"}
Sea $X$ una variable aleatoria con rango $R_X$. Una función definida por \[p(x)=P[X=x]= \sum^{}_{ \left\{\omega \in \Omega:X(\omega)=x\right\}}P\left[\left\{\omega\right\}\right]\]

1. $p(x)>0$, $x\in R_X$
1. $\sum_{x\in R_X}p(x)=P[X=x]=1$ 

```


El conjunto de pares ordenados $\left(x,p(x)\right)$, $x\in R_X$ recibe el nombre de *distribución de probabildiad de $X$*


```{example}
La variable aleatoria discreta 
\[p_X(x)=p(1-p)^{x-1}, \text{ $x\in \mathbb{Z}^+$ y $p\in[0,1]$}\]

en efecto \[p(1-p)^{i-1}>0, \text{ $\forall x\in \mathbb{Z}^+$}\] además  \[ \sum^{\infty}_{i=1}p(1-p)^{i-1}=p \lim_{n\to\infty}\frac{1-(1-p)^{n+1}}{1-(1-p)}=1\]
```

```{example}
La variable aleatoria discreta 
\[p_X(x)=p(1-p), \text{ $x\in \mathbb{Z}^+$ y $p\in[0,1]$}\]

en efecto \[p(1-p)^{i-1}>0, \text{ $\forall x\in \mathbb{Z}^+$}\] además  \[ \sum^{\infty}_{i=1}p(1-p)^{i-1}=p \lim_{n\to\infty}\frac{1-(1-p)^{n+1}}{1-(1-p)}=1\]
```

```{example}
La variable aleatoria discreta 
\[p_X(x)=(1-p)^{x-1}, \text{ $x\in \mathbb{Z}^+$ y $p\in[0,1]$}\]

en efecto \[p(1-p)^{i-1}>0, \text{ $\forall x\in \mathbb{Z}^+$}\] además  \[ \sum^{\infty}_{i=1}p(1-p)^{i-1}=p \lim_{n\to\infty}\frac{1-(1-p)^{n+1}}{1-(1-p)}=1\]
```

### Función de probabilidad de una variable aleatoria continua


```{definition,name="Función de densidad de probabilidad"}
Sea $X$ una variable aleatoria con rango $R_X$. La  función $f(x)$ definida sobre $R_X$ 
  
1. $f(x)>0$, $x\in R_X$ o $f(x)>0$, $x\in \mathbb{R}$
2. $\int_{R_X}f(x)dx=1$ o $\int_{-\infty}^{\infty}f(x)dx=1$ 

```

```{example,eval=TRUE,echo=TRUE}
For a circle with the radius `r x`,
its area is `r pi * x^2`.
Sea la función


```


\[\frac{1}{x^2}
=`r integrate(function(x) {1/(x^2)}, lower = 1, upper = Inf)$value`
\]

\[\frac{\sin x}{x^3}
=`r integrate(function(x) {sin(x)/(x^3)}, lower = 1, upper = 10)$value`
\]

\[\Phi_{\mu ,\sigma ^{2}}(x)=\frac {1}{\sigma {\sqrt {2\pi }}}e^{-{\frac {(u-\mu )^{2}}{2\sigma ^{2}}}}du
\]


```{example}
Sea $f(x)= \frac{\alpha}{\rho}$ es una funcion de densidad pues
  $$f(x)>0,~ x\in R_X$$ además
  $$\int_{R_X}f(x)dx=1$$
```

```{example}
Sea $f(x)= \frac{\sigma}{\rho}$ es una funcion de densidad pues
  $$f(x)>0,~ x\in R_X$$ además
  $$\int_{R_X}f(x)dx=1$$
```



## Función de distribución de una variable aleatoria 
### Función de distribución de una variable aleatoria discreta
```{definition,name="Función de distribución"}
Sea $X$ una variable aleatoria con rango $$R_X= \left\{x_1,x_2,\ldots x_n,\ldots\right\}.$$ Con función de probabilidad \(p(x_i)=P[X=x_i]\), sea $x$ cualquier número, real la función definida por \[F(x)=P[X\leq x]= \sum^{}_{x_i\leq x}p(x_i)= \sum^{}_{x_i\leq x}P[X= x_i]  \]
recie el nombre de función de distribución de $X$. Cuyas propiedades son:

1. \(0\leq F_X(x)\leq 1\)
2. \(F_X(-\infty)=0\)
3. \(F_X(\infty)=1\)
4. \(P(X<x)=F_X(x^-)\)
5. \(P(a\leq X\leq b)=F_X(b)-F_X(a^-)\)

```




```{example}
wwwwwww
```

```{example}
wwwwwww
```

```{example}
wwwwwww
```


### Función de distribución de una variable aleatoria continua


```{definition, name="Función de distribución"}
Sea $X$ una variable aleatoria con función de densidad $f(x)$. La función
\[F_X(x)=F(x)=P[X\leq x]=\int_{-\infty}^{x}f(t)dt, \text{ $\forall x\in R_X$}\]

Cuyas propiedades son:

1. \(0\leq F(x)\leq 1\)
2. \(F(-\infty)=0\)
3. \(F(\infty)=1\)

```


```{example}
wwwwwww
```

```{example}
wwwwwww
```

```{example}
wwwwwww
```


# Parámetros de una variable aleatoria
## Esperanza matemática

```{definition, name="Esperanza matemática de una variable aleatoria discreta"}
\[\mathbb{E}[X]=\sum _{i=1}^{n}x_{i}p(x_{i})\]
```

```{definition, name="Esperanza matemática de una variable aleatoria continua"}
\[\mathbb{E}[X]=\int_{-\infty }^{\infty}xf(x)dx \text{ equivalentemente }\mathbb {E}[X]=\int_{\Omega }X\,{\text{d}}P\]
```
el valor esperado a veces se representa por \(\mu =\mathbb {E} [X]\) que es el promedio o la media poblacional.

## Medidas de variación

La varianza es una medida de dispersión de una variable aleatoria $X$ respecto a su esperanza $\mathbb {E} [X]$. Se define como la esperanza de la transformación $$\rho=\text{Var}(X)=\left(X-\mathbb {E} [X]\right)^{2}$$

$$\sigma =\sqrt{\text{Var}(X)}$$ o bien $$\sigma^{2}=\text{Var}(X)$$


```{definition, name="Varianza de una variable aleatoria discreta"}
Sea 
```

```{definition, name="Varianza matemática de una variable aleatoria continua"}
Sea 
```

## Medidas de posición
```{definition, name="Cuantiles de una variable aleatoria discreta"}
Sea 
```

```{definition, name="Cuantiles matemática de una variable aleatoria continua"}
Sea 
```

## Medidas de curtosis
```{definition, name="Curtosis de una variable aleatoria discreta"}
Sea 
```

```{definition, name="Curtosis de una variable aleatoria continua"}
Sea 
```
momento de orden superior
\[{\displaystyle M_{X}^{(n)}=\mathbb {E} [X^{n}]=\int _{\mathbb {R} }x^{n}f_{X}(x)\ {\text{d}}x}\]





# Variables aleatorias bidimensionales

```{definition,name="Variable aleatoria bidmensional discreta"}
\[F(x,y)=P[X\leq x,Y\leq y]= \sum^{x}_{u=-\infty}\sum^{y}_{v=-\infty}=p(u,v)\]
```

```{example}

```

```{definition,name="Variable aleatoria bidmensional contínua"}
\[F(x,y)=P[X\leq x,Y\leq y]= \sum^{x}_{u=-\infty}\sum^{y}_{v=-\infty}=p(u,v)\]
```

```{example}

```
## Distribución bidimensional discreta

```{definition, name="Función de probabilidad conjunta"}
Sea $(X,Y)$ una variable bidimensinal discreta con rango $R_{X\times Y}$. A cada posible resultado le asociamos un numero $$p(x,y)=P[X=x, Y=y]$$ que cumple la siguientes condiciones

1. $1>p(x,y)>0$, $(x,y)\in R_{X\times Y}\in$
2. $\sum^{}_{x\in R_X} \sum^{}_{y\in R_Y}p(x,y)=1$

  Alos pares ordenados $\left((x,y),p(x,y)\right)$ se le llama **distribución de probabilidad conjunta**
```

```{definition,name="Función de distribución acumulada"}
\[F(x,y)=P[X\leq x,Y\leq y]= \sum^{x}_{u=-\infty}\sum^{y}_{v=-\infty}=p(u,v)\]
```

### Distribuciones marginales
### Variables aleatorias independientes
### Distribuciones de probabilidad condicional


## Distribución bidimensional continua











# Distribuciones discreta importantes
## Variable aleatoria discreta binomial
## Variable aleatoria discreta Poisson

















# Distribuciones continuas importantes
## Variable aleatoria continua normal
## Variable aleatoria continua gamma


# Distribuciones muestrales



# Estimación


# Prueba de hipótesis