# Organización de datos en tablas de frecuencias
```{r nice-fig, fig.cap='Here is a nice figure!', out.width='80%', fig.asp=.75, fig.align='center'}
library(extrafont) 
library(tidyverse)

# link www.fontsquirrel.com/fonts/latin-modern-roman

# execute once to add fonts:
font_import(pattern = "lmroman*") 

loadfonts()
data <- data.frame(x=1:10, y=1:10)
p <- data %>% ggplot(aes(x, y)) + geom_point() + 
    theme(text         = element_text(size=10, family="Times New Roman")) + ggtitle("for the boys")
p + theme(plot.subtitle = element_text(vjust = 1), 
    plot.caption = element_text(vjust = 1)) +labs(subtitle = "lil subtitle i guess", 
    caption = "Source: idk, 2018")

data(mtcars)
mtcars %>% ggplot(aes(x=mpg, y=disp)) + geom_col(aes(col=cyl)) + 
   theme(text         = element_text(size=10, family="Times New Roman")) + ggtitle("Organización de datos en tablas de frecuencias")

set.seed(1234)  # This makes R run the same random draw
df <- data_frame(x = rnorm(100),
                 y = rnorm(100))

# Create plot
p <- ggplot(df, aes(x = x, y = y)) +
  geom_point() +
  annotate("text", x = 0, y = 0, label = "This is some text",
           family = "Serif", color = "darkred", size = 8) +
  labs(title = "This is a title",
       subtitle = "This is a figure") +
  theme_light(base_family = "Times New Roman")
p
```
# Matriz y rango

# Distribució n de frecuencias
\[ \begin{pmatrix}
1&1&1&1\\
1&1&1&1\\
1&1&1&1
\end{pmatrix}\]
La tabulación es un proceso en el cual los datos son ordenados en grupos llamados *clases* para un análisis más eficaz de estos, los datos podrían estar clasificados mediante una variable cualitativa o cuantitativa en el caso de las variables cualitativas $Y_i$, se considera la siguiente Tabla \@ref(tab:ww)

Table: (\#tab:ww) Caption

| $Y_i$| $f_i$ | $F_i$ | $F_i^*$ | $h_i$ | $H_i$ | $H_i^*$ | $h_i\%$ | $H_i\%$ | $H_i^*\%$ 
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| $Y_1$ | $f_1$ | $F_1$ | $F_1^*$ | $\frac{f_1}{n}$ | $\frac{F_1}{n}$ | $\frac{F_1^*}{n}$|$h_1$|$H_1$|$H_1^*$|
| $Y_2$ | $f_2$ | $F_2$ | $F_2^*$ | $\frac{f_2}{n}$ | $\frac{F_2}{n}$ | $\frac{F_2^*}{n}$|$h_2$|$H_2$|$H_1^*$|
| $Y_3$ | $f_3$ | $F_3$ | $F_3^*$ | $\frac{f_3}{n}$ | $\frac{F_3}{n}$ | $\frac{F_3^*}{n}$|$h_3$|$H_3$|$H_1^*$|
| $\vdots$ | $\vdots$ | $\vdots$ | $\vdots$ |       $\vdots$ | $\vdots$ | $\vdots$|$\vdots$|$\vdots$|$\vdots$|$\vdots$|
| $Y_r$ | $f_r$ | $F_r$ |$F_r^*$ | $\frac{f_r}{n}$ | $\frac{F_r}{n}$ | $\frac{F_r^*}{n}$|$h_r$|$H_r$|$H_1^*$|

En el caso de variables cuantitativas ademas si los datos son muy variados,  que para se clasificados adecuadamente, necesitan generarse particiones de longitudes semejantes entonces se utiliza el siguiente proceso; el **número de las particiones** $r$ se consideran de acuerdo a **tres criterios** 

* Criterio del investigador $r$ no puede ser más de 20 ni menos de 5

* $r=\sqrt{n}$ donde $n$ es el número de datos

* La regla de Starges que consiste en considerar la fórmula $r=3.322\cdot\log_{10} n$ 
Una vez establecido el número  de particiones se procede a generar los límites laterales de cada una de las particiones, sea $L$ la longitud de todo el conjunto es decir $L=x_{\text{max}}-x_{\text{min}}$ entonces la longitud de las particiones o amplitud interválica  se obtiene con $l=\frac{L}{r}$

| Clase| Clase | $f_i$ | $F_i$ | $F_i^*$ | $h_i$ | $H_i$ | $H_i^*$ | $\ldots$ | $H_i\%$ | $H_i^*\%$ 
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| $[y_1-y_2>$ |$y_1$| $f_1$ | $F_1$ | $F_1^*$ | $\frac{f_1}{n}$ | $\frac{F_1}{n}$ | $\frac{F_1^*}{n}$|$\ldots$|$H_1$|$H_1^*$|
| $<y_1-y_2>$ |$y_2$| $f_2$ | $F_2$ | $F_2^*$ | $\frac{f_2}{n}$ | $\frac{F_2}{n}$ | $\frac{F_2^*}{n}$|$\ldots$|$H_2$|$H_1^*$|
| $<y_{r}-y_r>$ |$y_3$| $f_3$ | $F_3$ | $F_3^*$ | $\frac{f_3}{n}$ | $\frac{F_3}{n}$ | $\frac{F_3^*}{n}$|$\ldots$|$H_3$|$H_1^*$|
| $\vdots$ | $\vdots$ | $\vdots$ | $\vdots$ |       $\vdots$ | $\vdots$ | $\vdots$|$\vdots$|$\vdots$|$\vdots$|$\vdots$|
| $<y_{r-1}-y_r]$ |$y_r$| $f_r$ | $F_r$ |$F_r^*$ | $\frac{f_r}{n}$ | $\frac{F_r}{n}$ | $\frac{F_r^*}{n}$|$...$|$H_r$|$H_1^*$|

Tenga en cuenta que  $n$ es el número de datos, es decir $n=f_1+f_2+\ldots+f_r=\sum_{i=1}^r$ donde $f_i$ es número de datos en la partición $X_i$, una de las $r$ particiones del conjunto total de datos.


* Las **frecuencias absolutas**\index{frecuencias absolutas} $f_i$ indican el número de datos con la característica $X_i$.
* Las **frecuencias absolutas acumuladas menor que**\index{frecuencias absolutas acumuladas menor que} $F_i$ obedecen a la fórmula 
$$F_m=f_1+f_2+\ldots+f_m=\sum_{i=1}^mf_i$$
* Las **frecuencias absolutas acumuladas mayor que** $F_i^*$ obedecen a la fórmula 
$$F_m^*=f_m+f_{m+1}+\ldots+f_r=\sum_{i=m}^rf_i=n-\sum_{i=1}^{m-1}f_i=n-\left(f_1+f_{2}+\ldots+f_{m-1}\right)$$
* Las **frecuencias absolutas relativas**\index{frecuencias absolutas relativas}  obedecen a la fórmula 
$$h_m=\frac{f_m}{n}$$
* Las **frecuencias absolutas relativas  menor que**\index{frecuencias absolutas relativas  menor que} obedecen a la fórmula 
$$H_m=\frac{f_m}{n}$$
* Las **frecuencias absolutas relativas  mayor que** obedecen a la fórmula 
$$H_m^*=\frac{F_m}{n}$$



* Las **frecuencias absolutas relativas porcentuales** obedecen a la fórmula 
$h_i\%=100\cdot h_i$
* Las **frecuencias absolutas relativas  menor que porcentuales** obedecen a la fórmula 
$H_i\%=100\cdot H_i$
* Las **frecuencias absolutas relativas  mayor que porcentuales** obedecen a la fórmula 
$H_i^*\%=100\cdot H_i^*$

```{exercise}
Sean los datos 
```

```{solution}
Entonces
  
```



