# Gráficos estadísticos



# Medidas de tendencia central

Son aquellas medidas que buscan un dato representtivo central de un conjunto de datos tales como la media, la moda y la mediana.

## La media ($\overline{x}$)
A veces llamada _promedio aritmético_, es la medida de tendencia central que pondera los datos.

### Media de datos no agrupados
Los datos no están agrupados cuando no están ordenados sobre una tabla de distribución de frecuencias. Sean los $n$ datos $x_1, x_2,\ldots, x_n$ entonces la media o promedio aritmético se define como 
\begin{equation}
\overline{x}=\frac{x_1+x_2+\cdots+x_n}{n}=\frac{1}{n}\sum_{i=1}^nx_i
(\#eq:w1)
\end{equation}
\begin{equation}
\frac{d\left[P;F_1\right]}{d\left[P;\mathcal{L}_1\right]}=e=\frac{d\left[P;F_2\right]}{d\left[P;\mathcal{L}_2\right]}
(\#eq:ww)
\end{equation}

1. $\overline{x}=\frac{x_1+x_2+\cdots+x_n}{n}=\frac{1}{n}\sum_{i=1}^nx_i$
2. $\overline{x}=\frac{x_1+x_2+\cdots+x_n}{n}=\frac{1}{n}\sum_{i=1}^nx_i$ 


### Media de datos agrupados

Considérese la siguiente tabla de distribucion de frecuencias entonces el promedio es $$\overline{x}=\frac{y_1f_1+y_2f_2+\cdots+y_nf_n}{n}=\frac{1}{n}\sum_{i=1}^ny_if_i$$


| Clase| Clase | $f_i$ | $F_i$ | $F_i^*$ | $h_i$ | $H_i$ | $H_i^*$ | $\ldots$ | $H_i\%$ | $H_i^*\%$ 
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| $<y_1-y_2>$ |$y_1$| $f_1$ | $F_1$ | $F_1^*$ | $\frac{f_1}{n}$ | $\frac{F_1}{n}$ | $\frac{F_1^*}{n}$|$\ldots$|$H_1$|$H_1^*$|
| $<y_2-y_3>$ |$y_2$| $f_2$ | $F_2$ | $F_2^*$ | $\frac{f_2}{n}$ | $\frac{F_2}{n}$ | $\frac{F_2^*}{n}$|$\ldots$|$H_2$|$H_1^*$|
| $<y_3-y_4>$ |$y_3$| $f_3$ | $F_3$ | $F_3^*$ | $\frac{f_3}{n}$ | $\frac{F_3}{n}$ | $\frac{F_3^*}{n}$|$\ldots$|$H_3$|$H_1^*$|
| $\vdots$ | $\vdots$ | $\vdots$ | $\vdots$ |       $\vdots$ | $\vdots$ | $\vdots$|$\vdots$|$\vdots$|$\vdots$|$\vdots$|
| $<y_{r-1}-y_r]$ |$y_r$| $f_r$ | $F_r$ |$F_r^*$ | $\frac{f_r}{n}$ | $\frac{F_r}{n}$ | $\frac{F_r^*}{n}$|$...$|$H_r$|$H_1^*$|


```{exercise}
Si el promedio de $n$ datos es $\overline{x}$ entonces el promedio del conjunto inicial más un dato adicional $x_{n+1}$ es $$\overline{x}'=\frac{n\overline{x}+x_{n+1}}{n+1}$$ en general si se adicionan $r$ datos $y_1, y_2, \ldots y_r$ entonces el nuevo promedio será $$\overline{x}'=\frac{n\overline{x}+y_{1}+y_2+\ldots+y_r}{n+r}$$
```

```{solution}
En efecto sea el promedio 
\begin{align*}
\overline{x}'&=\frac{x_1+x_2+\cdots+x_{n+1}}{n+1}\\
&=\frac{n\frac{x_1+x_2+\cdots x_n}{n}+x_{n+1}}{n+1}\\
&=\frac{n\overline{x}+x_{n+1}}{n+1}
\end{align*}
````
## La moda (Mo)

### Moda de datos no tabulados
En este caso es dato que más repite en un conjunto de datos dados. 


La moda es el dato que más se repite por ejemplo sea el conjunto de datos $x_1,$ $x_2,$ $x_2,$ $x_2,$ $x_3$ entonces la moda $\text{Mo}=x_2$ 


### Moda de datos tabulados

La moda es el dato que más se repite por ejemplo sea el conjunto de datos $x_1,$ $x_2,$ $x_2,$ $x_2,$ $x_3$ entonces la moda $\text{Mo}=Li+\frac{Li-Ls}{Li+Ls}r$ 



| Clase| Clase | $f_i$ | $F_i$ | $F_i^*$ | $h_i$ | $H_i$ | $H_i^*$ | $\ldots$ | $H_i\%$ | $H_i^*\%$ 
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| $[y_1-y_2>$ |$y_1$| $f_1$ | $F_1$ | $F_1^*$ | $\frac{f_1}{n}$ | $\frac{F_1}{n}$ | $\frac{F_1^*}{n}$|$\ldots$|$H_1$|$H_1^*$|
| $<y_1-y_2>$ |$y_2$| $f_2$ | $F_2$ | $F_2^*$ | $\frac{f_2}{n}$ | $\frac{F_2}{n}$ | $\frac{F_2^*}{n}$|$\ldots$|$H_2$|$H_1^*$|
| $<y_{r}-y_r>$ |$y_3$| $f_3$ | $F_3$ | $F_3^*$ | $\frac{f_3}{n}$ | $\frac{F_3}{n}$ | $\frac{F_3^*}{n}$|$\ldots$|$H_3$|$H_1^*$|
| $\vdots$ | $\vdots$ | $\vdots$ | $\vdots$ |       $\vdots$ | $\vdots$ | $\vdots$|$\vdots$|$\vdots$|$\vdots$|$\vdots$|
| $<y_{r-1}-y_r]$ |$y_r$| $f_r$ | $F_r$ |$F_r^*$ | $\frac{f_r}{n}$ | $\frac{F_r}{n}$ | $\frac{F_r^*}{n}$|$...$|$H_r$|$H_1^*$|



## la mediana (Me)

### Mediana de datos no tabulados
Obtener la mediana consiste en ordenar los datos de menor a mayor y considerar dos casos: El prmero si el numero de datos s impar entonces el dato $x_{\frac{n+1}{2}}$ del conjunto ordenado será la mediana es decir $\text{Me}=x_{\frac{n+1}{2}}$ de otro lado si el número de datos es par entonces la mediana es la semisuma de los dos datos intermedios es decir $\text{Me}=\frac{x_{\frac{n}{2}}+x_{\frac{n}{2}+1}}{2}$

```{exercise}
Sean los conjuntos de datos 5, 6, 8, 2, 1, 5, 6, 7, 10, 0, 14 y 20, 25, 6, 5, 19, 5 obtener la mediana de estos conjuntos de datos.
```

```{solution}
Al ordenarlos  se obtiene el siguiente arreglo 0, 1, 2, 5, 5, 6, 6, 7, 8, 10, 14 y considerando que $x_1=0$, $x_2=1$, $\ldots$, $x_{11}=14$ en este caso el número de datos es impar entonces el dato $x_{\frac{11+1}{2}}=x_{6}=6$ el la mediana. De otro lado el segundo conjunto de datos al ser ordenados 5, 5, 6, 19, 20, 25 ademas considerando que $x_1=5$, $x_2=5$, $\ldots$, $x_6=25$ conducen a obtener la mediana $\text{Me}=\frac{x_{\frac{6}{2}}+x_{\frac{6}{2}+1}}{2}=\frac{6+19}{2}=12.5$.
```


### Mediana de datos tabulados



| Clase| Clase | $f_i$ | $F_i$ | $F_i^*$ | $h_i$ | $H_i$ | $H_i^*$ | $\ldots$ | $H_i\%$ | $H_i^*\%$ 
|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|:---:|
| $[y_1-y_2>$ |$y_1$| $f_1$ | $F_1$ | $F_1^*$ | $\frac{f_1}{n}$ | $\frac{F_1}{n}$ | $\frac{F_1^*}{n}$|$\ldots$|$H_1$|$H_1^*$|
| $<y_1-y_2>$ |$y_2$| $f_2$ | $F_2$ | $F_2^*$ | $\frac{f_2}{n}$ | $\frac{F_2}{n}$ | $\frac{F_2^*}{n}$|$\ldots$|$H_2$|$H_1^*$|
| $<y_{r}-y_r>$ |$y_3$| $f_3$ | $F_3$ | $F_3^*$ | $\frac{f_3}{n}$ | $\frac{F_3}{n}$ | $\frac{F_3^*}{n}$|$\ldots$|$H_3$|$H_1^*$|
| $\vdots$ | $\vdots$ | $\vdots$ | $\vdots$ |       $\vdots$ | $\vdots$ | $\vdots$|$\vdots$|$\vdots$|$\vdots$|$\vdots$|
| $<y_{r-1}-y_r]$ |$y_r$| $f_r$ | $F_r$ |$F_r^*$ | $\frac{f_r}{n}$ | $\frac{F_r}{n}$ | $\frac{F_r^*}{n}$|$...$|$H_r$|$H_1^*$|

Los pasos son:

* Se halla $\frac{n}{2}$ luego 
* $x_n$ 
* 
\[ \begin{pmatrix}
1&1&1&1\\
1&1&1&1\\
1&1&1&1
\end{pmatrix}\]
can be found on the Pandoc website http://pandoc.org.
\[\sum\]
> I thoroughly disapprove of duels. If a man should challenge me,
  I would take him kindly and forgivingly by the hand and lead him
  to a quiet place and kill him.

In this section, we give a very brief introduction to Pandoc’s Markdown. Readers who are familiar with Markdown can skip this section. The comprehensive syntax of Pandoc’s Markdown can be found on the Pandoc website http://pandoc.org. $\sum_1^2$

> I thoroughly disapprove of duels. If a man should challenge me,
  I would take him kindly and forgivingly by the hand and lead him
  to a quiet place and kill him.
>
> -- Mark Twain

$$\begin{pmatrix}\alpha & \beta\\
\gamma & \delta
\end{pmatrix}-\frac{2}{3} \begin{pmatrix}\alpha_1 & \beta_2\\
\gamma & \delta
\end{pmatrix}$$
* La suma de dos matrices $A_{n\times m}$ y $B_{r\times s}$ $$A_{n\times m}\pm B_{n\times m}=[a_{ij}+b_{ij}]$$
* El producto de dos matrices $A_{n\times m}$ y $B_{r\times s}$ $$A_{n\times m}\cdot B_{n\times m}=[a_{ij}+b_{ij}]$$
$$X = \begin{bmatrix}1 & x_{1}\\
1 & x_{2}\\
1 & x_{3}
\end{bmatrix}$$

$$\begin{vmatrix}a & b\\
c & d
\end{vmatrix}=ad-bc$$

$$\begin{array}{ccc}
x_{11} & x_{12} & x_{13}\\
x_{21} & x_{22} & x_{23}
\end{array}$$




# Medidas de dispersión
# Medidas de asimetría
