# (PART) Probabilidades {-}

# Experimento aleatorio

# Álgebra de eventos

# Técnicas de conteo

# Definición de probabilidad

# Probabilidad condicional

# Teorema de Bayes

# Eventos independientes y secuencias de experimentos

# Probabilidad en espacio
























# (PART)  Inferencia estadística {-}

# Variables aleatorias
```{definition,name="Variable aleatoria"}
Sea $\Omega$ un espacio muestral asociado a una experimento aleatorio $\epsilon$ y $\omega\in\Omega$,  entonces se genera la función **variable aleatoria** 
\begin{align*}
  X:\Omega&\longrightarrow \mathbb{R}\\
  \omega&\longmapsto X(\omega)
\end{align*}
```
es decir a cada elemento de $\Omega$ se le asocia un número real $\mathbb{R}$, además la probabilidad de $x\in \mathbb{R}$ es $P[x]= \sum^{n}_{i=1}P\left[\omega_i\right]$ donde $\omega_i\in X^{-1}(x)$. La definición indica por otro lado que un espacio muestral $\Omega$ puede genera diferentes variables aleatorias. Por ejemplo el espacio muestral de lanzar una monedas tres veces es $\omega= \left\{ccc,ccs,csc,scc,css,scs,ssc,sss\right\}$ además sea $n_c$ es número de caras y $n_s$ el número de sellos, es posibles generar dos o mas variables aleatorias por ejemplo:

* $X(\omega)=n_c$ entonces el rango de $X$ es $R_X \left\{3,2,1,0\right\}$
pues \begin{align*}
  3&=X(ccc)&\\
  2&=X(ccs)=X(csc)=X(scc)&\\
  1&=X(css)=X(scs)=X(ssc)&\\
  0&=X(sss)&
\end{align*}
* $X(\omega)=n_c-n_s$ entonces las imagenes de $X$ son $R_X= \left\{3,1,-1,-3\right\}$ en efecto 
\begin{align*}
  3&=X(ccc)&\\
  1&=X(ccs)=X(csc)=X(scc)&\\
  -1&=X(css)=X(scs)=X(ssc)&\\
  -3&=X(sss).&
\end{align*}

Estos subconjuntos de $\mathbb{R}$ también son espacios muestrales pues el conjunto de elementos de $\Omega$ con imagen dentro de estos valores reales $x$ en $\mathbb{R}$ es un elemento de $2^{\Omega}$ es decir un evento por lo tanto tiene una determinada probabilidad $P[x]$, en el primer caso $X(\omega)=n_c$ tienen probabilidades  
\begin{align*}
  P(3)&=P[ccc]= \frac{1}{8}\\
  P(2)&=P[ccs]=P[csc]=P[scc]=\frac{3}{8}\\
  P(1)&=P[css]=P[scs]=P[ssc]=\frac{3}{8}\\
  P(0)&=P[sss]=\frac{1}{8}
\end{align*}
que es lo mismo para el segundo caso $X(\omega)=n_c-n_s$.
```{definition,name="Eventos equivalentes"}
Sea $\Omega$ un espacio muestral asociado a una experimento aleatorio $\epsilon$ y $X$ una variable aleatoria con rango $R_X$ definida sobre $\Omega$. Dos eventos $W\in\Omega$ y $E_X\in R_X$ son **eventos equivalentes** si  existe la relación
\[W= \left\{\omega\in\Omega/X(\omega)=E_X\right\}\] es decir $E_X$ consta de todos los elementos en $\Omega$ para los cuales $X(\omega)\in W$
```
## Clases de variables aleatorias
### Variable aleatoria discreta
\(R_X\)  es *finitox* o *infinitopP* contable (no necesarimente enteros)
\(R_X= \left\{x_1,x_2,\ldots,x_n\ldots\right\}\)


\[p_X(x)=p(1-p)^{x-1}\] \(x\in \mathbb{Z}^+\) \(p\in[0,1]\)


\[F_X(x)=P[X=x]\]


* \(0\leq F_X(x)\leq 1\)
* \(F_X(-\infty)=0\)
* \(F_X(\infty)=1\)
* \(P(X<x)=F_X(x^-)\)
* \(P(a\leq X\leq b)=F_X(b)-F_X(a^-)\)



### Variable aleatoria continua

\(R_X\) abarca cualquier intervalo en la recta numerica

Sea $X$ una VA continua  con rango $R_{X}$
La funcion de densidad de probabilidad asociado a una variable aleatoria \(f(x)\)

* \(f(x)\leq 0\), $x\in R_{X}$
* \(\int_{R_{X}} f(x)dx=1\) o \(\int_{-\infty}^\infty f(x)dx=1\)





### Variable aleatoria mixta
Discreta y continua




## Función de probabilidad de una variable aleatoria 

### Función de probabilidad de una variable aleatorias discreta
```{definition,name="Funcion de probabilidad"}
Sea $X$ una variable aleatoria con rango $R_X$. Una funcion definida por \[p(x)=P[X=x]= \sum^{}_{ \left\{\omega \in \Omega:X(\omega)=x\right\}}P\left[\left\{\omega\right\}\right]\]

* $p(x)>0$, $x\in R_X$
* $\sum_{x\in R_X}p(x)=P[X=x]=1$ 

```
El conjunto de pares ordenados $\left(x,p(x)\right)$, $x\in R_X$ recibe el nombre de *distribución de probabildiad de $X$*

### Función de probabilidad de una variable aleatoria continua


```{definition,name="Función de densidad de probabilidad"}
Sea $X$ una variable aleatoria con rango $R_X$. La  función $f(x)$ definida sobre $R_X$ 
  
* $f(x)>0$, $x\in R_X$ o $f(x)>0$, $x\in \mathbb{R}$
* $\int_{R_X}f(x)dx=1$ o $\int_{-\infty}^{\infty}f(x)dx=1$ 

```

## Función de distribución de una variable aleatoria 
### Función de distribución de una variable aleatoria discreta
```{definition,name="Función de distribución"}
Sea $X$ una variable aleatoria con rango $R_X= \left\{x_1,x_2,\ldots x_n,\ldots\right\}$. Con función de probabilidad \(p(x_i)=P[X=x_i]\), sea $x$ cualquier número, real la función definida por \[F(x)=P[X\leq x]= \sum^{}_{x_i\leq x}p(x_i)= \sum^{}_{x_i\leq x}P[X= x_i]  \]
recie el nombre de función de distribución de $X$.
```

### Función de distribución de una variable aleatoria continua







# Estadigrafos de la variables aleatorias
## esperanza matematica
## Medidas de tendencia central
## Medidas de variación
## Cuantiles

# Variables aleatorias bidimensionales
## Distribuciones marginales
## Distribuciones
# Distribuciones discreta importantes
## Variable aleatoria discreta binomial
## Variable aleatoria discreta Poisson


# Distribuciones continuas importantes
## Variable aleatoria continua normal
## Variable aleatoria continua gamma


# Distribuciones muestrales

# Estimación

# Prueba de hipótesis