--- 
title: "Geometria-vectorial"
author: "Ricardo Michel MALLQUI BAÑOS"
institute: "Universidad Nacional San Cristóbal De Huamanga"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: krantz
fontsize: 10pt
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
subparagraph: yes
description: ""
---
\newcommand{\N}{\mathbb{N}}
\newcommand{\R}{\mathbb{R}}
\newcommand{\CC}{\mathbb{C}}
\newcommand{\I}{\mathbb{I}}
\newcommand{\f}{\mathbb{f}}
\newcommand{\X}{\mathbb{X}}
\newcommand{\D}{\mathbb{D}}
\newcommand{\Z}{\mathbb{Z}}
\newcommand{\Q}{\mathbb{Q}}
\newcommand{\norm}[1]{\left\Vert#1\right\Vert}
\newcommand{\abs}[1]{\left\vert#1\right\vert}
\newcommand{\set}[1]{\left\{#1\right\}}
\newcommand{\seq}[1]{\left<#1\right>}
\newcommand{\co}[1]{\left[#1\right]}
\newcommand{\cc}[1]{\left(#1\right)}
\newcommand{\J}{\mathcal{J}}
\newcommand{\K}{\mathcal{K}}
\newcommand{\M}{\mathcal{M}}
\newcommand{\F}{\mathcal{F}}

# Resumen {-}
Consideramos que es un “sistema” en tanto integra el conjunto de
conocimientos
 objetivos
 de
 una
 misma
 naturaleza
 que
 están
interrelacionados y que interactúan mutuamente.
Es un “producto de la actividad del hombre” dado que el conocimiento
se adquiere, en primera instancia a partir de la práctica, en un proceso que
va de la contemplación viva al pensamiento abstracto y de este a la práctica
como forma de verificación.
Tiene un “carácter histórico y en permanente cambio” debido a que la
ciencia no es estática, va surgiendo bajo determinadas circunstancias y
momentos históricos, y se desarrolla en evolución permanente, apoyándose
en las necesidades de la sociedad humana y a partir de los cambios que se
producen en la naturaleza, la sociedad y el pensamiento.
Por su parte el término “investigar” no es más que “hacer diligencias para
descubrir algo; profundizar en el estudio de una disciplina” 6
.
La “investigación”
 expresa el modo de llegar al conocimiento de algo,
siguiendo un camino de forma sistemática, utilizando métodos propios de la
ciencia o de la actividad científica. La investigación “... aparece estrechamente
ligada a la vida social, intelectual, tecnológica y cultural; constituyéndose en un
factor inseparable de cualquier actividad cognoscitiva u operación mental que se
realice para abordar un problema, duda o curiosidad”.7
La investigación se concibe como un procedimiento reflexivo, dirigido,
controlado, sistemático y crítico que permite llegar a descubrir nuevos
hechos, datos, relaciones o leyes, en cualquier campo del conocimiento
humano.

Consideramos que es un “sistema” en tanto integra el conjunto de
conocimientos
 objetivos
 de
 una
 misma
 naturaleza
 que
 están
interrelacionados y que interactúan mutuamente.
Es un “producto de la actividad del hombre” dado que el conocimiento
se adquiere, en primera instancia a partir de la práctica, en un proceso que
va de la contemplación viva al pensamiento abstracto y de este a la práctica
como forma de verificación.
Tiene un “carácter histórico y en permanente cambio” debido a que la
ciencia no es estática, va surgiendo bajo determinadas circunstancias y
momentos históricos, y se desarrolla en evolución permanente, apoyándose
en las necesidades de la sociedad humana y a partir de los cambios que se
producen en la naturaleza, la sociedad y el pensamiento.
Por su parte el término “investigar” no es más que “hacer diligencias para
descubrir algo; profundizar en el estudio de una disciplina” 6
.
La “investigación”
 expresa el modo de llegar al conocimiento de algo,
siguiendo un camino de forma sistemática, utilizando métodos propios de la
ciencia o de la actividad científica. La investigación “... aparece estrechamente
ligada a la vida social, intelectual, tecnológica y cultural; constituyéndose en un
factor inseparable de cualquier actividad cognoscitiva u operación mental que se
realice para abordar un problema, duda o curiosidad”.7
La investigación se concibe como un procedimiento reflexivo, dirigido,
controlado, sistemático y crítico que permite llegar a descubrir nuevos
hechos, datos, relaciones o leyes, en cualquier campo del conocimiento
humano.

Consideramos que es un “sistema” en tanto integra el conjunto de
conocimientos
 objetivos
 de
 una
 misma
 naturaleza
 que
 están
interrelacionados y que interactúan mutuamente.
Es un “producto de la actividad del hombre” dado que el conocimiento
se adquiere, en primera instancia a partir de la práctica, en un proceso que
va de la contemplación viva al pensamiento abstracto y de este a la práctica
como forma de verificación.
Tiene un “carácter histórico y en permanente cambio” debido a que la
ciencia no es estática, va surgiendo bajo determinadas circunstancias y
momentos históricos, y se desarrolla en evolución permanente, apoyándose
en las necesidades de la sociedad humana y a partir de los cambios que se
producen en la naturaleza, la sociedad y el pensamiento.
Por su parte el término “investigar” no es más que “hacer diligencias para
descubrir algo; profundizar en el estudio de una disciplina” 6
.
La “investigación”
 expresa el modo de llegar al conocimiento de algo,
siguiendo un camino de forma sistemática, utilizando métodos propios de la
ciencia o de la actividad científica. La investigación “... aparece estrechamente
ligada a la vida social, intelectual, tecnológica y cultural; constituyéndose en un
factor inseparable de cualquier actividad cognoscitiva u operación mental que se
realice para abordar un problema, duda o curiosidad”.7
La investigación se concibe como un procedimiento reflexivo, dirigido,
controlado, sistemático y crítico que permite llegar a descubrir nuevos
hechos, datos, relaciones o leyes, en cualquier campo del conocimiento
humano.

# Introducción{-}
Consideramos que es un “sistema” en tanto integra el conjunto de
conocimientos
 objetivos
 de
 una
 misma
 naturaleza
 que
 están
interrelacionados y que interactúan mutuamente.
Es un “producto de la actividad del hombre” dado que el conocimiento
se adquiere, en primera instancia a partir de la práctica, en un proceso que
va de la contemplación viva al pensamiento abstracto y de este a la práctica
como forma de verificación.
Tiene un “carácter histórico y en permanente cambio” debido a que la
ciencia no es estática, va surgiendo bajo determinadas circunstancias y
momentos históricos, y se desarrolla en evolución permanente, apoyándose
en las necesidades de la sociedad humana y a partir de los cambios que se
producen en la naturaleza, la sociedad y el pensamiento.
Por su parte el término “investigar” no es más que “hacer diligencias para
descubrir algo; profundizar en el estudio de una disciplina” 6
.
La “investigación”
 expresa el modo de llegar al conocimiento de algo,
siguiendo un camino de forma sistemática, utilizando métodos propios de la
ciencia o de la actividad científica. La investigación “... aparece estrechamente
ligada a la vida social, intelectual, tecnológica y cultural; constituyéndose en un
factor inseparable de cualquier actividad cognoscitiva u operación mental que se
realice para abordar un problema, duda o curiosidad”.7
La investigación se concibe como un procedimiento reflexivo, dirigido,
controlado, sistemático y crítico que permite llegar a descubrir nuevos
hechos, datos, relaciones o leyes, en cualquier campo del conocimiento
humano.

Consideramos que es un “sistema” en tanto integra el conjunto de
conocimientos
 objetivos
 de
 una
 misma
 naturaleza
 que
 están
interrelacionados y que interactúan mutuamente.
Es un “producto de la actividad del hombre” dado que el conocimiento
se adquiere, en primera instancia a partir de la práctica, en un proceso que
va de la contemplación viva al pensamiento abstracto y de este a la práctica
como forma de verificación.
Tiene un “carácter histórico y en permanente cambio” debido a que la
ciencia no es estática, va surgiendo bajo determinadas circunstancias y
momentos históricos, y se desarrolla en evolución permanente, apoyándose
en las necesidades de la sociedad humana y a partir de los cambios que se
producen en la naturaleza, la sociedad y el pensamiento.
Por su parte el término “investigar” no es más que “hacer diligencias para
descubrir algo; profundizar en el estudio de una disciplina” 6
.
La “investigación”
 expresa el modo de llegar al conocimiento de algo,
siguiendo un camino de forma sistemática, utilizando métodos propios de la
ciencia o de la actividad científica. La investigación “... aparece estrechamente
ligada a la vida social, intelectual, tecnológica y cultural; constituyéndose en un
factor inseparable de cualquier actividad cognoscitiva u operación mental que se
realice para abordar un problema, duda o curiosidad”.7
La investigación se concibe como un procedimiento reflexivo, dirigido,
controlado, sistemático y crítico que permite llegar a descubrir nuevos
hechos, datos, relaciones o leyes, en cualquier campo del conocimiento
humano.

Consideramos que es un “sistema” en tanto integra el conjunto de
conocimientos
 objetivos
 de
 una
 misma
 naturaleza
 que
 están
interrelacionados y que interactúan mutuamente.
Es un “producto de la actividad del hombre” dado que el conocimiento
se adquiere, en primera instancia a partir de la práctica, en un proceso que
va de la contemplación viva al pensamiento abstracto y de este a la práctica
como forma de verificación.
Tiene un “carácter histórico y en permanente cambio” debido a que la
ciencia no es estática, va surgiendo bajo determinadas circunstancias y
momentos históricos, y se desarrolla en evolución permanente, apoyándose
en las necesidades de la sociedad humana y a partir de los cambios que se
producen en la naturaleza, la sociedad y el pensamiento.
Por su parte el término “investigar” no es más que “hacer diligencias para
descubrir algo; profundizar en el estudio de una disciplina” 6
.
La “investigación”
 expresa el modo de llegar al conocimiento de algo,
siguiendo un camino de forma sistemática, utilizando métodos propios de la
ciencia o de la actividad científica. La investigación “... aparece estrechamente
ligada a la vida social, intelectual, tecnológica y cultural; constituyéndose en un
factor inseparable de cualquier actividad cognoscitiva u operación mental que se
realice para abordar un problema, duda o curiosidad”.7
La investigación se concibe como un procedimiento reflexivo, dirigido,
controlado, sistemático y crítico que permite llegar a descubrir nuevos
hechos, datos, relaciones o leyes, en cualquier campo del conocimiento
humano.

# Preliminares{-}
Consideramos que es un “sistema” en tanto integra el conjunto de
conocimientos
 objetivos
 de
 una
 misma
 naturaleza
 que
 están
interrelacionados y que interactúan mutuamente.
Es un “producto de la actividad del hombre” dado que el conocimiento
se adquiere, en primera instancia a partir de la práctica, en un proceso que
va de la contemplación viva al pensamiento abstracto y de este a la práctica
como forma de verificación.
Tiene un “carácter histórico y en permanente cambio” debido a que la
ciencia no es estática, va surgiendo bajo determinadas circunstancias y
momentos históricos, y se desarrolla en evolución permanente, apoyándose
en las necesidades de la sociedad humana y a partir de los cambios que se
producen en la naturaleza, la sociedad y el pensamiento.
Por su parte el término “investigar” no es más que “hacer diligencias para
descubrir algo; profundizar en el estudio de una disciplina” 6
.
La “investigación”
 expresa el modo de llegar al conocimiento de algo,
siguiendo un camino de forma sistemática, utilizando métodos propios de la
ciencia o de la actividad científica. La investigación “... aparece estrechamente
ligada a la vida social, intelectual, tecnológica y cultural; constituyéndose en un
factor inseparable de cualquier actividad cognoscitiva u operación mental que se
realice para abordar un problema, duda o curiosidad”.7
La investigación se concibe como un procedimiento reflexivo, dirigido,
controlado, sistemático y crítico que permite llegar a descubrir nuevos
hechos, datos, relaciones o leyes, en cualquier campo del conocimiento
humano.

Consideramos que es un “sistema” en tanto integra el conjunto de
conocimientos
 objetivos
 de
 una
 misma
 naturaleza
 que
 están
interrelacionados y que interactúan mutuamente.
Es un “producto de la actividad del hombre” dado que el conocimiento
se adquiere, en primera instancia a partir de la práctica, en un proceso que
va de la contemplación viva al pensamiento abstracto y de este a la práctica
como forma de verificación.
Tiene un “carácter histórico y en permanente cambio” debido a que la
ciencia no es estática, va surgiendo bajo determinadas circunstancias y
momentos históricos, y se desarrolla en evolución permanente, apoyándose
en las necesidades de la sociedad humana y a partir de los cambios que se
producen en la naturaleza, la sociedad y el pensamiento.
Por su parte el término “investigar” no es más que “hacer diligencias para
descubrir algo; profundizar en el estudio de una disciplina” 6
.
La “investigación”
 expresa el modo de llegar al conocimiento de algo,
siguiendo un camino de forma sistemática, utilizando métodos propios de la
ciencia o de la actividad científica. La investigación “... aparece estrechamente
ligada a la vida social, intelectual, tecnológica y cultural; constituyéndose en un
factor inseparable de cualquier actividad cognoscitiva u operación mental que se
realice para abordar un problema, duda o curiosidad”.7
La investigación se concibe como un procedimiento reflexivo, dirigido,
controlado, sistemático y crítico que permite llegar a descubrir nuevos
hechos, datos, relaciones o leyes, en cualquier campo del conocimiento
humano.
